Asana 1200098726617751 : Contraindre à payer l'échéance précédente en…
emilschn/yproject-site-wptheme pull request #191
Opened 2021-04-01 10:22 UTC by hmeneuvrier

… premier

2021-04-01 16:05 UTC, emilschn requested changes

2021-04-01 16:05 UTC, emilschn commented on pages/controler/controler-tableau-de-bord.php
> +				ypcf_debug_log( 'controler-tableau-de-bord.php :: $declaration->set_is_first_declaration_to_pay() '.json_encode($declaration->is_first_declaration_to_pay()));
Supprimer le log :)

Dans le principe, ça me semble bien, j'aurais fait un truc similaire, je pense.
J'aurais fait ça en PHP aussi. 
J'aurais appelé la fonction set_is_payable pour être moins restrictif. Mais c'est du détail !

2021-04-02 07:12 UTC, hmeneuvrier commented on pages/controler/controler-tableau-de-bord.php
> +				ypcf_debug_log( 'controler-tableau-de-bord.php :: $declaration->set_is_first_declaration_to_pay() '.json_encode($declaration->is_first_declaration_to_pay()));
Cool !! J'étais vraiment pas sûre de moi ! :)

2021-04-02 07:24 UTC, hmeneuvrier commented on pages/controler/controler-tableau-de-bord.php
> +				ypcf_debug_log( 'controler-tableau-de-bord.php :: $declaration->set_is_first_declaration_to_pay() '.json_encode($declaration->is_first_declaration_to_pay()));
C'est fait! (pourquoi je ne les vois jamais les logs au moment où je vérifie mon commit?)

2021-04-06 15:51 UTC, merged