Animation sur les boutons de la rubrique "Mon compte"
emilschn/yproject-site-wptheme pull request #193
Opened 2021-04-09 14:32 UTC by Lucasdnd

Les animations sont bonnes sur les boutons de la partie "mon compte", j'ai aussi fait la modif pour les paramètres des orga, par contre je crois qu'il y a un petit soucis pour le gif du loading, il s'affiche sur certains boutons mais pas d'autres, alors que l'arborescence ne change pas. Je ne sais pas si le soucis reste en prod ou c'est seulement en local. (j'ai tester pourtant de rajouter des "../" mais sans succès)

2021-04-12 15:56 UTC, hmeneuvrier requested changes

2021-04-12 15:56 UTC, hmeneuvrier commented on pages/view/common/form-identitydocs.php
> +<form method="POST" enctype="multipart/form-data" class="<?php echo $page_controler->get_form_css_classes();?> account-form">
Ajouter global $stylesheet_directory_uri; tout au début du fichier

2021-04-12 15:56 UTC, hmeneuvrier commented on pages/view/common/form-orga-bank.php
> +	<form method="POST" enctype="multipart/form-data" class="<?php echo $page_controler->get_form_css_classes();?> account-form" action="<?php echo admin_url( 'admin-post.php?action=user_account_organiz
Ajouter global $stylesheet_directory_uri; tout au début du fichier

2021-04-12 15:56 UTC, hmeneuvrier commented on pages/view/common/form-orga-bank.php
> +			</span>
peut-être pas common.next comme texte, mais peut-être un saving

2021-04-12 15:56 UTC, hmeneuvrier commented on pages/view/common/form-orga-identitydocs.php
> +<form method="POST" enctype="multipart/form-data" class="<?php echo $page_controler->get_form_css_classes();?> account-form" action="<?php echo admin_url( 'admin-post.php?action=user_account_organiza
Ajouter global $stylesheet_directory_uri; tout au début du fichier

2021-04-12 15:56 UTC, hmeneuvrier commented on pages/view/common/form-orga-parameters.php
> +<form method="POST" class="<?php echo $page_controler->get_form_css_classes();?> account-form" action="<?php echo admin_url( 'admin-post.php?action=user_account_organization_details' ); ?>" novalidat
Ajouter global $stylesheet_directory_uri; tout au début du fichier

2021-04-12 15:56 UTC, hmeneuvrier commented on pages/view/common/form-parameters.php
> +<form method="POST" enctype="multipart/form-data" class="<?php echo $page_controler->get_form_css_classes();?> account-form">
Ajouter global $stylesheet_directory_uri; tout au début du fichier

2021-04-12 15:56 UTC, hmeneuvrier commented on pages/view/mon-compte/content-orga-wallet.php
> +		</span>
registering ?

2021-04-12 15:56 UTC, hmeneuvrier commented on pages/view/mon-compte/content-wallet.php
> +			<img class="alignverticalmiddle marginright" src="<?php echo $stylesheet_directory_uri; ?>/images/loading-grey.gif" width="30" alt="chargement" /><?php _e( 'common.NEXT', 'yproject' ); ?>
il faudrait plutôt garder INVEST avec ...

2021-04-12 15:56 UTC, hmeneuvrier commented on pages/view/common/form-orga-bank.php
> +			</span>
ou registering

2021-04-12 15:56 UTC, hmeneuvrier commented on pages/view/mon-compte/content-user-notifications.php
> +<form method="POST" enctype="multipart/form-data" class="db-form v3 full bg-white form-register account-form">
Ajouter global $stylesheet_directory_uri; tout au début du fichier

2021-04-12 15:56 UTC, hmeneuvrier commented on pages/view/mon-compte/content-bank.php
> +	<form method="POST" enctype="multipart/form-data" class="db-form v3 full account-form">
Ajouter global $stylesheet_directory_uri; tout au début du fichier

2021-04-13 12:42 UTC, Lucasdnd commented on pages/view/mon-compte/content-orga-wallet.php
> +		</span>
C'est le bouton Investir qui se trouve dans le porte monnaie je pense que Suivant est le plus approprié puisqu'il n'y a pas d'enregistrement ou de sauvegarde 
( voici le bouton en question [https://ibb.co/1Z2gHjw] )

2021-04-13 13:00 UTC, Lucasdnd commented on pages/view/mon-compte/content-wallet.php
> +			<img class="alignverticalmiddle marginright" src="<?php echo $stylesheet_directory_uri; ?>/images/loading-grey.gif" width="30" alt="chargement" /><?php _e( 'common.NEXT', 'yproject' ); ?>
Je n'ai pas vraiment compris ce commentaire, car le texte du bouton doit rester investir il est bien placé non ?

2021-04-13 14:00 UTC, merged