Feature/show investissements pending
emilschn/yproject-site-wptheme pull request #201
Opened 2021-04-29 14:30 UTC by Lucasdnd

Avant lorsqu'un utilisateur non authentifié évaluait un projet et faisait une intention d'investissement, il ne pouvait pas les consulter dans la partie "Mes investissement" de son compte . Désormais, ses intentions de préinvestissement apparaissent mais il ne peut pas les finaliser. Un message lui indiquant qu'il doit finir son authentification pour investir apparait ainsi qu'un bouton le redirigeant  vers cette rubrique (le cadre du message est un peu grand, Héloïse m'a dit que pour le moment ça pouvait rester comme ça, mais que dans tout les cas, ça sera amené à changer avec la nouvelle charte graphique)

2021-04-29 15:35 UTC, emilschn requested changes

2021-04-29 15:35 UTC, emilschn commented on pages/controler/controler-mon-compte.php
> +		if ( $this->current_user ) {
pourquoi tu as laissé ce if ? il est peut-être inutile à présent ? tu voulais tester si la valeur était bien définie ? si oui, tu peux tester !empty dessus

2021-05-25 13:52 UTC, hmeneuvrier requested changes

2021-05-25 13:52 UTC, hmeneuvrier commented on languages/en_US.po
> +msgstr "Authenticate my account"
@Lucasdnd il y a une erreur ici, il faut que ce soit "account.investments.ACCOUNT_AUTHENTICATION" comme dans le fr_FR.po
je le corrige

2021-05-25 13:59 UTC, merged