Asana 1194370981353025 : Changer l'affichage pour les projets ayant atteint l'objectif maximum
emilschn/yproject-site-wptheme pull request #235
Opened 2021-06-30 10:16 UTC by hmeneuvrier

2021-06-30 13:20 UTC, emilschn requested changes

2021-06-30 13:20 UTC, emilschn commented on projects/single/banner.php
> +									<?php _e( "Seuil maximum atteint: il n'est plus possible d'investir !", 'yproject' ); ?>
dans les règles de ponctuation, il y a un espace avant le ":" ;)
Et il faudrait traduire la chaine dans les fichiers po

2021-06-30 13:20 UTC, emilschn commented on projects/single/banner.php
> +							<a href="<?php echo WDG_Redirect_Engine::override_get_page_url( 'les-projets' ); ?>" class="button red"><?php _e("D&eacute;couvrir d'autres projets", "yproject" ) ?></a>
c'est traduit ?

2021-07-01 07:30 UTC, hmeneuvrier commented on projects/single/banner.php
> +									<?php _e( "Seuil maximum atteint: il n'est plus possible d'investir !", 'yproject' ); ?>
ahh mais oui...

2021-07-01 07:38 UTC, hmeneuvrier commented on projects/single/banner.php
> +							<a href="<?php echo WDG_Redirect_Engine::override_get_page_url( 'les-projets' ); ?>" class="button red"><?php _e("D&eacute;couvrir d'autres projets", "yproject" ) ?></a>
oui c'est un copié/collé

2021-07-01 07:47 UTC, hmeneuvrier commented on projects/single/banner.php
> +									<?php _e( "Seuil maximum atteint: il n'est plus possible d'investir !", 'yproject' ); ?>
fait

2021-07-01 10:08 UTC, merged